channels:
    - conda-forge
    - bioconda
dependencies:
    - python=3.11.5
    - snakemake=7.32.4
    - ipython
    - jupyter
    - numpy
    - pandas
    - scipy
    - matplotlib
    - seaborn
    - rpy2
    - scanpy
    - bedtools
    - pybedtools
    - biopython
    - r:r
    - r-msm
    - r-reticulate
    - rdata
    - bioconductor-biomart
    - pip
    #- pip:
    #    - cigma
