channels:
    - conda-forge
    - bioconda
dependencies:
    - python=3.11.5
    - snakemake=7.32.4
    - ipython
    - jupyter
    - numpy
    - pandas
    - scipy
    - matplotlib
    - seaborn
    - scanpy=1.11.5
    - bedtools=2.31.1
    - pybedtools=0.12.0
    - biopython
    - r:r
    - r-msm
    - r-reticulate
    - r-optparse
    - r-numderiv
    - r-matrix
    - rdata=1.0.0
    - bioconductor-biomart
    - pip
    - pip:
       - cigma
